[project]
name = "gym-management-backend"
version = "0.1.0"
description = "Gym Management System Backend"
requires-python = ">=3.11"
authors = [
    {name = "Bikotoru, Santiagoe16"}
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta" 