"""fix_plan_role_enum_case

Revision ID: 1c8289acc6a0
Revises: ebe47b0e7b46
Create Date: 2025-08-05 17:54:21.317034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '1c8289acc6a0'
down_revision = 'ebe47b0e7b46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, update existing data to use uppercase values
    op.execute("UPDATE plans SET role = 'REGULAR' WHERE role = 'regular'")
    op.execute("UPDATE plans SET role = 'TAQUILLERO' WHERE role = 'taquillero'")
    
    # Drop the old enum column
    op.drop_column('plans', 'role')
    
    # Add the new enum column with uppercase values
    op.add_column('plans', sa.Column('role', sa.Enum('REGULAR', 'TAQUILLERO', name='planrole'), nullable=False))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Update data back to lowercase
    op.execute("UPDATE plans SET role = 'regular' WHERE role = 'REGULAR'")
    op.execute("UPDATE plans SET role = 'taquillero' WHERE role = 'TAQUILLERO'")
    
    # Drop the new enum column
    op.drop_column('plans', 'role')
    
    # Add back the old enum column with lowercase values
    op.add_column('plans', sa.Column('role', sa.Enum('regular', 'taquillero', name='planrole'), nullable=False))
    
    # ### end Alembic commands ### 