"""remove_days_from_plan

Revision ID: 24dc92c403d9
Revises: 457c23e72bc7
Create Date: 2025-08-13 17:22:35.099117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24dc92c403d9'
down_revision = '457c23e72bc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('days', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 