"""remove_unique_from_Plan_name_columen

Revision ID: 3257d9d81eff
Revises: bed31e57d791
Create Date: 2025-08-17 16:38:46.784201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3257d9d81eff'
down_revision = 'bed31e57d791'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plans_name', table_name='plans')
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.create_index('ix_plans_name', 'plans', ['name'], unique=False)
    # ### end Alembic commands ### 