"""add_duration_day_to_user_plan

Revision ID: 457c23e72bc7
Revises: d1a53b024ca6
Create Date: 2025-08-12 10:31:54.260971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457c23e72bc7'
down_revision = 'd1a53b024ca6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_plans', sa.Column('duration_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_plans', 'duration_days')
    # ### end Alembic commands ### 