"""add_fingerprint1_fingerprint2_to_User

Revision ID: 7ba66fe9e508
Revises: 8b921e48e1b3
Create Date: 2025-08-20 17:03:36.272873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba66fe9e508'
down_revision = '8b921e48e1b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fingerprint1', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('fingerprint2', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fingerprint2')
    op.drop_column('users', 'fingerprint1')
    # ### end Alembic commands ### 