"""add_days_to_user_plan

Revision ID: bed31e57d791
Revises: 457c23e72bc7
Create Date: 2025-08-13 18:16:55.867920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed31e57d791'
down_revision = '457c23e72bc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_plans', sa.Column('days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_plans', 'days')
    # ### end Alembic commands ### 