"""add_check_in_time_to_attendance

Revision ID: c9b11593d0db
Revises: f73bfd2551f0
Create Date: 2025-08-01 23:59:22.486259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b11593d0db'
down_revision = 'f73bfd2551f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if columns exist before adding them
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('attendance')]
    
    # Add check_in_time column if it doesn't exist
    if 'check_in_time' not in columns:
        op.add_column('attendance', sa.Column('check_in_time', sa.DateTime(), nullable=True))
        op.execute("UPDATE attendance SET check_in_time = NOW() WHERE check_in_time IS NULL")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if columns exist before removing them
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('attendance')]
    
    # Remove check_in_time column if it exists
    if 'check_in_time' in columns:
        op.drop_column('attendance', 'check_in_time')
    
    # ### end Alembic commands ### 