"""change_schedule_fields_to_string

Revision ID: e93698f4f811
Revises: af2806227591
Create Date: 2025-07-29 11:34:41.258955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e93698f4f811'
down_revision = 'af2806227591'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'schedule_start',
               existing_type=mysql.TIME(),
               type_=sa.String(10),
               existing_nullable=True)
    op.alter_column('users', 'schedule_end',
               existing_type=mysql.TIME(),
               type_=sa.String(10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'schedule_end',
               existing_type=sa.String(10),
               type_=mysql.TIME(),
               existing_nullable=True)
    op.alter_column('users', 'schedule_start',
               existing_type=sa.String(10),
               type_=mysql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ### 