"""update_attendance_endpoint_and_spanish_translations

Revision ID: ebe47b0e7b46
Revises: c9b11593d0db
Create Date: 2025-08-05 17:22:41.136954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebe47b0e7b46'
down_revision = 'c9b11593d0db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First update any NULL gym_id values in attendance table
    op.execute("""
        UPDATE attendance a 
        JOIN users u ON a.user_id = u.id 
        SET a.gym_id = u.gym_id 
        WHERE a.gym_id IS NULL
    """)
    
    # Now make gym_id NOT NULL
    op.alter_column('attendance', 'gym_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    
    # Check if columns exist before adding them
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    plan_columns = [col['name'] for col in inspector.get_columns('plans')]
    
    # Add new columns to plans table if they don't exist
    if 'role' not in plan_columns:
        op.add_column('plans', sa.Column('role', sa.Enum('regular', 'taquillero', name='planrole'), nullable=False))
        # Update existing plans to have default role
        op.execute("UPDATE plans SET role = 'regular' WHERE role IS NULL")
    
    if 'days' not in plan_columns:
        op.add_column('plans', sa.Column('days', sa.Integer(), nullable=True))
    
    # Change column types for user schedule fields
    op.alter_column('users', 'schedule_start',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'schedule_end',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'schedule_end',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('users', 'schedule_start',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('plans', 'days')
    op.drop_column('plans', 'role')
    op.alter_column('attendance', 'gym_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ### 